Repository gyptazy/ProxLB, pull requests merged in 2024-10, with the labels that each got.

#87 feature: Add maintenance mode to evacuate a node and move workloads for other nodes in the cluster.
  .changelogs/1.0.4/58_add_maintenance_mode.yml
  README.md
  proxlb
  proxlb.conf
Labels: feature

#90 feature: Add version output as cli arg
  .changelogs/1.0.4/89_add_version_output.yml
  README.md
  proxlb
Labels: feature

#92 feature: Add feature to make API timeout configureable
  .changelogs/1.0.4/91_make_api_timeout_configureable.yml
  README.md
  proxlb
Labels: feature

#93 fix: Fix CPU balancing where calculations are done in float instead of int.
  .changelogs/1.0.4/75_fix_cpu_balancing.yml
  proxlb
Labels: bug

#96 release: Create stable release 1.0.4
  .changelogs/1.0.4/release_meta.yml
  CHANGELOG.md
  README.md
  packaging/CMakeLists.txt
  packaging/changelog_debian
  packaging/changelog_redhat
  proxlb
Labels: release

#105 fix(docs): Change docs to make bool usage in configs more clear.
  .changelogs/1.0.5/104_docs_bool_adjustment.yml
  .changelogs/1.0.5/release_meta.yml
  CONTRIBUTING.md
  README.md
Labels: documentation

#113 Allow migration from local disks
  .changelogs/1.0.5/113_fix_migration_from_local_disk.yml
  proxlb
Labels: feature

#116 release: Create release 1.0.5
  .changelogs/1.0.5/104_docs_bool_adjustment.yml
  .changelogs/1.0.5/107_fix_offline_node_eval.yml
  .changelogs/1.0.5/113_fix_migration_from_local_disk.yml
  .changelogs/1.0.5/98_fix_log_verbosity_opts.yml
  .changelogs/1.0.5/release_meta.yml
  .changelogs/1.0.6/release_meta.yml
  CHANGELOG.md
  README.md
  packaging/CMakeLists.txt
  packaging/changelog_debian
  packaging/changelog_redhat
  proxlb
Labels: release
