Repository gyptazy/ProxLB, pull requests merged in 2024-07, with the labels that each got.

#2 release(0.9.9): Prepare public development release 0.9.9
  .changelogs/0.9.0/1_initial_release.yaml
  .changelogs/0.9.0/release_meta.yml
  .changelogs/0.9.9/1_initial_release.yaml
  .changelogs/0.9.9/release_meta.yml
  .gitignore
  CHANGELOG.md
  README.md
  docs/01_Installation.md
  docs/02_Configuration.md
  docs/03_FAQ.md
  packaging/01_package.sh
  packaging/02_changelog_only.sh
  packaging/CMakeLists.txt
  packaging/README.md
  packaging/changelog_debian
  packaging/changelog_redhat
  packaging/postinst
  packaging/proxlb.service
  proxlb
  proxlb.conf
  tests/README.md
  tests/tests.py
Labels: release

#10 Add support for Docker container
  .gitignore
  Dockerfile
  README.md
  requirements.txt
Labels: feature

#9 feature(tags): Add tag evaluation to provide new features
  .changelogs/1.0.0/3_create_grouping_include_feature.yml
  .changelogs/1.0.0/4_create_grouping_exclude_feature.yml
  .changelogs/1.0.0/7_ignore_vm_by_tag_proxlb_ignore_vm.yml
  .changelogs/1.0.0/7_ignore_vms_by_wildcard.yml
  .changelogs/1.0.0/release_meta.yml
  README.md
  docs/02_Configuration.md
  proxlb
Labels: feature

#12 docs(container): Add docs for container (e.g., Docker, Prodman) support
  .changelogs/1.0.0/10_add_container_support.yml
  Dockerfile
  README.md
  docs/01_Installation.md
Labels: documentation

#14 feature(github-workflows): Add initial github workflows
  .flake8
  .github/workflows/02-create-package.yml
  packaging/01_package.sh
Labels: feature

#13 feature: Add dry-run support to see what kind of rebalancing would be done
  .changelogs/1.0.0/6_add_dry_run_support.yml
  README.md
  proxlb
Labels: feature

#20 fix-readme
  README.md
Labels: documentation

#22 feature(logging): Add configurable log verbosity. [#17]
  .changelogs/1.0.0/17-add-configurable-log-verbosity.yml
  README.md
  proxlb
  proxlb.conf
Labels: feature

#23 feature: Add option to rebalance VMs by their assigned resources. [#16]
  .changelogs/1.0.0/16_add_rebalancing_by_assigned_resources.yml
  README.md
  docs/02_Configuration.md
  proxlb
  proxlb.conf
Labels: feature

#28 feature(core): Add support for LXC/Container to be rebalanced.
  .changelogs/1.0.0/10_add_container_support.yml
  .changelogs/1.0.0/27_add_container_lxc_support.yml
  README.md
  proxlb
Labels: feature

#34 feature: Add new mode_option to rebalance by node's bytes or percent.
  .changelogs/1.0.0/29_add_option_rebalance_by_node_percent.yml
  README.md
  proxlb
Labels: feature
