Repository gyptazy/ProxLB, pull requests merged in 2025-04, with the labels that each got.

#166 fix: Fix tag evluation for VMs for being ignored for further balancing
  .changelogs/1.1.1/163_fix_ignore_vm_tag.yml
  .changelogs/1.1.1/165_improve_logging_servity.yml
  .changelogs/1.1.1/release_meta.yml
  proxlb/models/balancing.py
  proxlb/models/calculations.py
Labels: bug

#171 fix: path correction for docker entrypoint
  Dockerfile
Labels: bug

#172 changelog: Add changelog for: Fix Python 3 path for Docker entrypoint
  .changelogs/1.1.1/171_set_correct_python_path_docker_image.yml
Labels: documentation

#178 fix: Honor the value when balancing should not be performed and stop balancing.
  .changelogs/1.1.1/174_honor_balancing_activation_value.yml
  proxlb/main.py
Labels: bug

#179 docs: Adjust docs regarding API Token and privilege separation.
  docs/03_configuration.md
Labels: documentation

#182 change: Change the default banalcing mode to used instead of assigned.
  .changelogs/1.1.1/168_add_more_flexible_schedules.yml
  .changelogs/1.1.1/174_honor_balancing_activation_value.yml
  .changelogs/1.1.1/176_change_turn_daemon_mode_on_default.yml
  .changelogs/1.1.1/180_change_default_balancing_to_used_instead_assigned.yml
  README.md
  config/proxlb_example.yaml
Labels: feature

#188 fix: allow use of minutes instead of hours
  .changelogs/1.1.1/187_allow_use_of_minutes_instead_of_hours.yml
  proxlb/utils/helper.py
Labels: bug

#191 Feature: Add validation for the minimum required permissions of a user in Proxmox.
  .changelogs/1.1.1/184_validate_for_sufficient_user_permissions.yml
  proxlb/utils/proxmox_api.py
Labels: feature

#190 Minor typo fixes
  README.md
  docs/03_configuration.md
  proxlb/models/balancing.py
  proxlb/models/calculations.py
  proxlb/models/tags.py
  proxlb/utils/proxmox_api.py
Labels: documentation

#186 fix: logging handler for no systemd integration
  .changelogs/1.1.1/185-logging-handler-for-no-systemd-integration.yml
  proxlb/utils/logger.py
Labels: feature

#192 tecdebt: Improve logging handler creation
  .changelogs/1.1.1/185-logging-handler-for-no-systemd-integration.yml
  .changelogs/1.1.1/187_allow_use_of_minutes_instead_of_hours.yml
  proxlb/utils/logger.py
Labels: feature

#194 Main
  proxlb/utils/proxmox_api.py
Labels: documentation

#196 fix: set cpu_used to be cpu usage times number of cpu cores
  .changelogs/1.1.1/195_set_cpu_used_to_cpu_usage_times_core_count.yml
  proxlb/models/guests.py
  proxlb/models/nodes.py
Labels: bug

#198 fix: Use method/mode in configuration to calculate lowest_usage_node
  .changelogs/1.1.1/197_remove_hard_coded_memory_usage_from_lowest_usage_node.yml
  proxlb/models/calculations.py
Labels: bug

#199 docs: Add documentation about ignore guests such like VMs or CTs.
  README.md
  docs/03_configuration.md
Labels: documentation

#204 Fix default configuration file path in README.md
  README.md
Labels: documentation

#202 fix: Requery a guest if that running guest reports 0 cpu usage
  .changelogs/1.1.1/200_requery_zero_guest_cpu_used.yml
  proxlb/models/guests.py
Labels: bug

#210 docs: * Fix the rendering of the possible values of the ProxLB option…
  README.md
  docs/03_configuration.md
Labels: documentation

#212 release: Create release 1.1.1
  .changelogs/1.1.1/release_meta.yml
  CHANGELOG.md
  README.md
  debian/changelog
Labels: release

#213 release: Prepare release v1.1.2
  .changelogs/1.1.2/release_meta.yml
  debian/changelog
  misc/01-replace-version.sh
  proxlb/utils/version.py
  setup.py
Labels: release

#219 feature: Add possibility to pin guests to a specific hypervisor node.
  .changelogs/1.1.2/218_add_1_to_one_relationship_guest_node_pinning.yml
  README.md
  docs/03_configuration.md
  proxlb/models/calculations.py
  proxlb/models/guests.py
  proxlb/models/tags.py
Labels: feature

#220 feature: Add a retry mechanism when connecting to the Proxmox API
  .changelogs/1.1.2/157_add_proxmox_api_retry_mechanism.yml
  README.md
  config/proxlb_example.yaml
  proxlb/utils/proxmox_api.py
Labels: feature

#221 fix: Adjust the systemd unit file to run after the network target on non PVE nodes
  .changelogs/1.1.2/137_fix_systemd_unit_file.yml
  service/proxlb.service
Labels: bug
