Repository gyptazy/ProxLB, pull requests merged in 2025-07, with the labels that each got.

#261 feature: Allow custom (instead of static tcp/8006) API ports for API hosts
  .changelogs/1.1.5/260_allow_custom_api_ports.yml
  proxlb/utils/helper.py
  proxlb/utils/proxmox_api.py
Labels: feature

#264 Docs/custom api port
  README.md
  docs/03_configuration.md
Labels: documentation

#267 release: Create release 1.1.5
  .changelogs/1.1.5/release_meta.yml
  CHANGELOG.md
  README.md
  debian/changelog
  proxlb/utils/version.py
  setup.py
Labels: release

#270 docs: Adjust docs regarding maintenance node hostnames
  README.md
  docs/03_configuration.md
Labels: documentation

#274 docs: Add compatibility matrix of tested Proxmox versions
  README.md
Labels: documentation
